set_dataminingList_form:
    path:     /setDataminingList
    defaults: { _controller: DataminingBundle:Default:setDataminingList }
    methods:  POST
    
get_dataminingList_form:
    path:     /getDataminingList
    defaults: { _controller: DataminingBundle:Default:getDataminingList }
    methods:  POST
    
set_dataminingListVideo_form:
    path:     /setDataminingListVideo
    defaults: { _controller: DataminingBundle:Default:setDataminingListVideo }
    methods:  POST
    
get_dataminingListVideo_form:
    path:     /getDataminingListVideo
    defaults: { _controller: DataminingBundle:Default:getDataminingListVideo }
    methods:  POST