get_info_about_video_form:
    path:     /getInfoAboutVideo
    defaults: { _controller: VideoBundle:Default:getInfoAboutVideo }
    methods:  POST
    
get_comment_about_video_form:
    path:     /getCommentAboutVideo
    defaults: { _controller: VideoBundle:Default:getCommentAboutVideo }
    methods:  POST
    
add_like_video_form:
    path:     /addLikeVideo
    defaults: { _controller: VideoBundle:Default:addLikeVideo }
    methods:  POST
            
add_dislike_video_form:
    path:     /addDislikeVideo
    defaults: { _controller: VideoBundle:Default:addDislikeVideo }
    methods:  POST
        
add_comment_video_form:
    path:     /addCommentVideo
    defaults: { _controller: VideoBundle:Default:addCommentVideo }
    methods:  POST
    
increase_comments_amount_video_form:
    path:     /increaseCommentsAmountVideo
    defaults: { _controller: VideoBundle:Default:increaseCommentsAmountVideo }
    methods:  POST
    
read_lyrics_form:
    path:     /readLyrics
    defaults: { _controller: VideoBundle:Default:readLyrics }
    methods:  POST